# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0002_auto_20160722_1847'),
        ('bancos', '0002_auto_20160714_1358'),
        ('cargos', '0003_auto_20160721_1420'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField()),
                ('correo_personal', models.EmailField(blank=True, max_length=100)),
                ('celular_personal', models.CharField(blank=True, max_length=100)),
                ('profesion', models.CharField(blank=True, max_length=100)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('fecha_terminacion', models.DateField(blank=True, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, max_length=100)),
                ('eps', models.CharField(blank=True, max_length=100)),
                ('pension', models.CharField(blank=True, max_length=100)),
                ('arl', models.CharField(blank=True, max_length=100)),
                ('oculto', models.BooleanField(default=False)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bancos.Banco')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Cargo')),
                ('region', models.ManyToManyField(to='region.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateField(auto_now=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=1000)),
                ('oculto', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, upload_to='Formadores/Soportes/')),
                ('formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formadores.Formador')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soporte_formador', to='rh.TipoSoporte')),
            ],
        ),
    ]
