# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('departamentos', '0001_initial'),
        ('formadores', '0002_auto_20160728_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desplazamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BigIntegerField()),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_destino_desplazamiento', to='departamentos.Departamento')),
                ('departamento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_origen_desplazamiento', to='departamentos.Departamento')),
                ('municipio_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_destino_desplazamiento', to='municipios.Municipio')),
                ('municipio_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_origen_desplazamiento', to='municipios.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(default='revision', max_length=100)),
                ('observacion', models.TextField(blank=True, max_length=1000, null=True)),
                ('valor', models.BigIntegerField()),
                ('terminada', models.BooleanField(default=False)),
                ('valor_aprobado', models.BigIntegerField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Transportes/Solicitudes/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='Transportes/Pdf/')),
                ('desplazamientos', models.ManyToManyField(blank=True, null=True, to='formadores.Desplazamiento')),
                ('formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formador_solicitud_transporte', to='formadores.Formador')),
            ],
        ),
    ]
