# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formadores', '0003_desplazamiento_solicitudtransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='desplazamiento',
            name='motivo',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formador',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudtransporte',
            name='valor_aprobado_lider',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
