# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('formadores', '0004_auto_20160818_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='formador',
            name='codigo_ruta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formador',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='departamento_formador', to='departamentos.Departamento'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='formador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formador_grupos', to='formadores.Formador'),
        ),
    ]
