# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0005_auto_20160826_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupos',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='desplazamiento',
            name='motivo',
            field=models.CharField(max_length=600),
        ),
    ]
