# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0006_auto_20160831_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formador',
            name='cedula',
            field=models.BigIntegerField(unique=True),
        ),
    ]
