# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0007_auto_20160915_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='formador',
            name='primera_capacitacion',
            field=models.BooleanField(default=False),
        ),
    ]
