# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_contratos_valorentregable'),
        ('formadores', '0008_formador_primera_capacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('valor_entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ValorEntregable')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='formador',
            name='cantidad_docentes',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='revision',
            name='formador_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formadores.Formador'),
        ),
        migrations.AddField(
            model_name='revision',
            name='productos',
            field=models.ManyToManyField(blank=True, to='formadores.Producto'),
        ),
    ]
