# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0009_auto_20160919_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formadores.Cortes'),
        ),
    ]
