# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0010_auto_20160920_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortes',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Cortes'),
        ),
    ]
