# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0013_formador_usuario_colombia_aprende'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='desplazamientos',
            field=models.ManyToManyField(blank=True, to='formadores.Desplazamiento'),
        ),
    ]
