# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0014_auto_20161003_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtransporte',
            name='aprobacion_lider',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtransporte',
            name='creacion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
