# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0004_auto_20160728_1439'),
        ('formadores', '0016_formador_expedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formador',
            name='respaldo_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respaldo_cargo', to='cargos.Cargo'),
        ),
    ]
