# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0004_auto_20160728_1439'),
        ('formadores', '0017_formador_respaldo_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formador',
            name='cargo',
        ),
        migrations.AddField(
            model_name='formador',
            name='cargo',
            field=models.ManyToManyField(to='cargos.Cargo'),
        ),
    ]
