# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_tiposoporte_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formadores', '0018_auto_20161205_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('renuncia', models.BooleanField(default=False)),
                ('soporte_renuncia', models.FileField(blank=True, null=True, upload_to='Contratos/Formadores/Soporte Renuncia/')),
                ('liquidado', models.BooleanField(default=False)),
                ('soporte_liquidacion', models.FileField(blank=True, null=True, upload_to='Contratos/Formadores/Soporte Liquidacion/')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudSoportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('soportes_requeridos', models.ManyToManyField(to='rh.TipoSoporte')),
            ],
        ),
        migrations.AddField(
            model_name='formador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sistema_formador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='formador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formadores.Formador'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='soportes_requeridos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formadores.SolicitudSoportes'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formadores.Contrato'),
        ),
    ]
