# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0019_auto_20170214_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortesFormadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='Cohortes/Formadores/Archivo/')),
                ('resultado', models.FileField(upload_to='Cohortes/Formadores/Resultado/')),
                ('contratos', models.FileField(upload_to='Cohortes/Formadores/Contratos/')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_firmado',
            field=models.FileField(blank=True, null=True, upload_to='Contratos/Formadores/Contrato Firmado/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_original',
            field=models.FileField(blank=True, null=True, upload_to='Contratos/Formadores/Contrato Original/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
