# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formadores', '0020_auto_20170516_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='meta_beneficiarios',
            field=models.BigIntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='municipios',
            field=models.ManyToManyField(to='municipios.Municipio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='supervisores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vigencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grupos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grupos',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
