# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_region_departamentos'),
        ('formadores', '0023_contrato_tipo_contrato_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='region.Region'),
            preserve_default=False,
        ),
    ]
