# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentesmineducacion',
            name='cedula',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='docentesmineducacion',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento'),
        ),
        migrations.AlterField(
            model_name='docentesmineducacion',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio'),
        ),
        migrations.AlterField(
            model_name='docentesmineducacion',
            name='radicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radicados.Radicado'),
        ),
    ]
