# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_auto_20160729_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentesDocentic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('formador', models.CharField(max_length=100)),
                ('cedula_formador', models.BigIntegerField()),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
    ]
