# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_auto_20160801_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentesdocentic',
            name='directivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docentesdocentic',
            name='informatica',
            field=models.BooleanField(default=False),
        ),
    ]
