# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_auditoria', models.IntegerField()),
                ('codigo_municipio', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('oculto', models.BooleanField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
