# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_auto_20160722_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposoporte',
            options={'ordering': ['nombre']},
        ),
    ]
