# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0001_initial'),
        ('rh', '0003_auto_20160728_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('codigo_ruta', models.CharField(max_length=100)),
                ('observacion_solicitante', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula', models.BigIntegerField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hv', models.FileField(blank=True, null=True, upload_to='Cantidatos/Hv')),
                ('observacion_respuesta', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_solicitud_contratacion', models.DateTimeField(blank=True, null=True)),
                ('observacion_final', models.TextField(blank=True, max_length=500, null=True)),
                ('remitido_respuesta', models.BooleanField(default=False)),
                ('remitido_contratacion', models.BooleanField(default=False)),
                ('contratar', models.BooleanField(default=False)),
                ('desierto', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_requerimiento', to=settings.AUTH_USER_MODEL)),
                ('municipios', models.ManyToManyField(to='municipios.Municipio')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
