# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_requerimientopersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientopersonal',
            name='contratado',
            field=models.BooleanField(default=False),
        ),
    ]
