# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_requerimientopersonal_contratado'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientopersonal',
            name='contrato_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
