# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_requerimientopersonal_contrato_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposoporte',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
