# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_entregable_escencial'),
        ('region', '0002_auto_20160728_1439'),
        ('formadores', '0014_auto_20161003_0851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrices', '0003_beneficiario_usuario_colombia_aprende'),
        ('evidencias', '0002_auto_20160915_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='Evidencias/Soportes')),
                ('beneficiarios_cargados', models.ManyToManyField(related_name='beneficiarios_cargados', to='matrices.Beneficiario')),
                ('beneficiarios_validados', models.ManyToManyField(blank=True, related_name='beneficiarios_validados', to='matrices.Beneficiario')),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregable_diplomado', to='productos.Entregable')),
                ('formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formadores.Formador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='codigoevidencia',
            name='beneficiarios',
        ),
        migrations.RemoveField(
            model_name='codigoevidencia',
            name='entregable',
        ),
        migrations.RemoveField(
            model_name='codigoevidencia',
            name='red',
        ),
        migrations.AddField(
            model_name='red',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='region.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='red',
            name='retroalimentacion',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CodigoEvidencia',
        ),
        migrations.AddField(
            model_name='red',
            name='evidencias',
            field=models.ManyToManyField(related_name='evidencia_red', to='evidencias.Evidencia'),
        ),
    ]
