# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0003_auto_20161003_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='red',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='red',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Formatos Red/'),
        ),
        migrations.AlterField(
            model_name='red',
            name='evidencias',
            field=models.ManyToManyField(blank=True, related_name='evidencia_red', to='evidencias.Evidencia'),
        ),
        migrations.AlterField(
            model_name='red',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
