# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 01:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidencias', '0004_auto_20161004_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('excel', models.FileField(upload_to='Evidencias/Carga Masiva/Excel')),
                ('zip', models.FileField(upload_to='Evidencias/Carga Masiva/Zip')),
                ('resultado', models.FileField(blank=True, null=True, upload_to='Evidencias/Carga Masiva/Resultado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cargamasiva', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
