# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0005_cargamasiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='archivo_retroalimentacion',
            field=models.FileField(blank=True, null=True, upload_to='Formatos Red/Retroalimentacion/'),
        ),
    ]
