# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0003_beneficiario_usuario_colombia_aprende'),
        ('evidencias', '0006_red_archivo_retroalimentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, max_length=1000)),
                ('red_id', models.IntegerField()),
                ('evidencia_id', models.IntegerField()),
                ('beneficiario_rechazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrices.Beneficiario')),
            ],
        ),
        migrations.AddField(
            model_name='evidencia',
            name='beneficiarios_rechazados',
            field=models.ManyToManyField(blank=True, related_name='beneficiarios_rechazados', to='evidencias.Rechazo'),
        ),
    ]
