# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidencias', '0007_auto_20161020_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsanacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, max_length=1000)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidencias.Evidencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
