# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0009_auto_20161227_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='red_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
