# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0008_auto_20170613_1528'),
        ('evidencias', '0010_evidencia_red_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='beneficiarios',
            field=models.ManyToManyField(blank=True, related_name='beneficiarios_red', to='matrices.Beneficiario'),
        ),
        migrations.AddField(
            model_name='red',
            name='producto_final',
            field=models.BooleanField(default=False),
        ),
    ]
