# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models

def create_initial(apps, schema_editor):
    Banco = apps.get_model("bancos","Banco")
    bancos = ['Banco de bogotá',
              'Banco popular',
              'Corpbanca',
              'Bancolombia',
              'Citibank',
              'BBVA',
              'Helm',
              'Colpatria',
              'Banco de occidente',
              'Banco caja social',
              'Banco agrario',
              'Davivienda',
              'Av villas',
              'Bancamia',
              'Banco pichincha',
              'Bancoomeva',
              'Banaco falabella',
              'Banaco finandina'
             ]
    for banco in bancos:
        new = Banco(nombre=banco)
        new.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(create_initial),
    ]
