# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'permissions': (('rh', 'Recursos Humanos'),)},
        ),
    ]
