# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_auto_20160714_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={},
        ),
    ]
