# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_auto_20160721_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nombre']},
        ),
    ]
