# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-01 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0006_entregable_escencial'),
        ('region', '0003_region_departamentos'),
        ('municipios', '0001_initial'),
        ('formadores', '0022_contrato_codigo_ruta'),
        ('secretarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dane_sede_text', models.CharField(blank=True, max_length=1000)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField(unique=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaneSEDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dane_sede', models.BigIntegerField(unique=True)),
                ('nombre_sede', models.CharField(max_length=200)),
                ('dane_ie', models.BigIntegerField()),
                ('nombre_ie', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretarias.Secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_vigencia_2017', to='formadores.Contrato')),
                ('diplomado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Diplomado')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='dane_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigencia2017.DaneSEDE'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_beneficiario_vigencia_2017', to='vigencia2017.Grupos'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_beneficiario_vigencia_2017', to='region.Region'),
        ),
    ]
