# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigencia2017', '0003_auto_20170803_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorentregablevigencia2017',
            name='valor',
            field=models.FloatField(default=0, null=True),
        ),
    ]
