# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-25 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_entregable_escencial'),
        ('region', '0003_region_departamentos'),
        ('formadores', '0023_contrato_tipo_contrato_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vigencia2017', '0005_auto_20170811_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='Evidencias/Vigencia 2017/Soportes')),
                ('subsanacion', models.BooleanField(default=False)),
                ('cantidad_cargados', models.IntegerField(blank=True, null=True)),
                ('red_id', models.IntegerField(blank=True, null=True)),
                ('corte_id', models.IntegerField(blank=True, null=True)),
                ('beneficiarios_cargados', models.ManyToManyField(related_name='vigencia_2017_beneficiarios_cargados', to='vigencia2017.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigencia2017.Beneficiario')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigencia2017.Evidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Rechazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, max_length=1000)),
                ('red_id', models.IntegerField()),
                ('evidencia_id', models.IntegerField()),
                ('beneficiario_rechazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigencia2017.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('retroalimentacion', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Formatos Red/Vigencia 2017/')),
                ('archivo_retroalimentacion', models.FileField(blank=True, null=True, upload_to='Formatos Red/Vigencia 2017/Retroalimentacion/')),
                ('producto_final', models.BooleanField(default=False)),
                ('beneficiarios', models.ManyToManyField(blank=True, related_name='vigencia_2017_beneficiarios_red', to='vigencia2017.Beneficiario')),
                ('diplomado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_2017_diplomdo', to='productos.Diplomado')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_2017_region', to='region.Region')),
            ],
        ),
        migrations.AddField(
            model_name='grupos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Evidencias/Vigencia 2017/No Conectividad'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='no_conectividad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='beneficiarios_rechazados',
            field=models.ManyToManyField(blank=True, related_name='vigencia_2017_beneficiarios_rechazados', to='vigencia2017.Rechazo'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='beneficiarios_validados',
            field=models.ManyToManyField(blank=True, related_name='vigencia_2017_beneficiarios_validados', to='vigencia2017.Beneficiario'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formadores.Contrato'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='entregable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_2017_entregable_diplomado', to='productos.Entregable'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_2017_usuario_evidencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
