# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-27 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('vigencia2017', '0007_auto_20170827_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='dane_sede_text',
        ),
        migrations.RemoveField(
            model_name='beneficiariocambio',
            name='dane_sede_text',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio'),
        ),
        migrations.AddField(
            model_name='beneficiariocambio',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio'),
        ),
    ]
