# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0024_contrato_region'),
        ('vigencia2017', '0010_corte_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='contrato',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, to='formadores.Contrato'),
            preserve_default=False,
        ),
    ]
