# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigencia2017', '0011_pago_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='completa',
            field=models.BooleanField(default=False),
        ),
    ]
