# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField()),
                ('nombre_sede', models.CharField(max_length=200)),
                ('dane_sede', models.BigIntegerField()),
                ('tipo', models.IntegerField()),
                ('ubicacion', models.IntegerField()),
                ('oculto', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre_sede'],
            },
        ),
    ]
