# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('radicados', '0002_radicado_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicado',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio'),
            preserve_default=False,
        ),
    ]
