# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('radicados', '0003_radicado_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadicadoRetoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField()),
                ('ubicacion', models.CharField(max_length=300)),
                ('institucion', models.CharField(max_length=300)),
                ('sede', models.CharField(max_length=300)),
                ('nombre_completo', models.CharField(max_length=300)),
                ('dane', models.BigIntegerField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
