# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-01 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicados', '0004_radicadoretoma'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicado',
            name='dane_ie',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radicado',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='radicado',
            name='ie_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radicado',
            name='matricula',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radicado',
            name='nombre_ie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='radicado',
            name='sede_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radicado',
            name='zona',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='radicado',
            name='dane_sede',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radicado',
            name='nombre_sede',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='radicado',
            name='numero',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='radicado',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radicado',
            name='ubicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
