# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20160728_1439'),
        ('lideres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lideres',
            name='region',
        ),
        migrations.AddField(
            model_name='lideres',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='region.Region'),
            preserve_default=False,
        ),
    ]
