# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_tiposoporte_categoria'),
        ('municipios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0001_initial'),
        ('lideres', '0002_auto_20160826_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('renuncia', models.BooleanField(default=False)),
                ('soporte_renuncia', models.FileField(blank=True, null=True, upload_to='Contratos/Lideres/Soporte Renuncia/')),
                ('liquidado', models.BooleanField(default=False)),
                ('soporte_liquidacion', models.FileField(blank=True, null=True, upload_to='Contratos/Lideres/Soporte Liquidacion/')),
            ],
        ),
        migrations.CreateModel(
            name='Desplazamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BigIntegerField()),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=600)),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_destino_desplazamiento_lider', to='departamentos.Departamento')),
                ('departamento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_origen_desplazamiento_lider', to='departamentos.Departamento')),
                ('municipio_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_destino_desplazamiento_lider', to='municipios.Municipio')),
                ('municipio_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_origen_desplazamiento_lider', to='municipios.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudSoportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('soportes_requeridos', models.ManyToManyField(related_name='tipo_soporte_lider', to='rh.TipoSoporte')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('creacion_date', models.DateTimeField(blank=True, null=True)),
                ('aprobacion_lider', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='revision', max_length=100)),
                ('observacion', models.TextField(blank=True, max_length=1000, null=True)),
                ('valor', models.BigIntegerField()),
                ('terminada', models.BooleanField(default=False)),
                ('valor_aprobado', models.BigIntegerField(blank=True, null=True)),
                ('valor_aprobado_lider', models.BigIntegerField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Transportes/Solicitudes/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='Transportes/Pdf/')),
                ('desplazamientos', models.ManyToManyField(blank=True, to='lideres.Desplazamiento')),
            ],
        ),
        migrations.AddField(
            model_name='lideres',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sistema_lider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtransporte',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider_solicitud_transporte_lider', to='lideres.Lideres'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lideres.Lideres'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='soportes_requeridos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lideres.SolicitudSoportes'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lideres.Contrato'),
        ),
    ]
