# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentespreinscritos',
            name='fecha',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 8, 2, 20, 50, 22, 636000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
