# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0002_docentespreinscritos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentespreinscritos',
            name='masivo',
            field=models.BooleanField(default=False),
        ),
    ]
