# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0003_docentespreinscritos_masivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentespreinscritos',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docentespreinscritos',
            name='docentes_innovadores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docentespreinscritos',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
