# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0004_actividades'),
        ('formadores', '0004_auto_20160818_1748'),
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaCronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sedes', models.IntegerField()),
                ('beneficiados', models.IntegerField()),
                ('fecha', models.DateField()),
                ('institucion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('actividades_entrada', models.ManyToManyField(blank=True, related_name='actividades_cronograma', to='productos.Actividades')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento')),
                ('formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formadores.Formador')),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
