# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0002_auto_20160826_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradacronograma',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
