# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20160714_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('usuarios', 'Administracion de usuarios'),)},
        ),
    ]
