# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('web', models.URLField()),
                ('oculto', models.BooleanField(default=False)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
