# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models

def create_initial(apps, schema_editor):
    Region = apps.get_model("region","Region")
    defaults = [
        {'nombre':'Región 1','numero':1},
        {'nombre':'Región 2','numero':2}
    ]
    for default in defaults:
        new = Region(nombre=default['nombre'], numero = default['numero'])
        new.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.RunPython(create_initial),
    ]
