# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nombre']},
        ),
    ]
