# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('region', '0002_auto_20160728_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='departamentos',
            field=models.ManyToManyField(to='departamentos.Departamento'),
        ),
    ]
