# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_entregable_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='formato',
            field=models.FileField(blank=True, null=True, upload_to='Entregables/Formatos'),
        ),
    ]
