# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_entregable_formato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('horas', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_sesion', to='productos.Sesion')),
            ],
        ),
    ]
