# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_contratos_valorentregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='escencial',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
