# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radicados', '0004_radicadoretoma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_solicitud', models.FileField(blank=True, null=True, upload_to='Acceso/Retoma/Seleccion')),
                ('cantidad_equipos', models.IntegerField(blank=True)),
                ('estado_seleccion', models.CharField(default='Revision', max_length=100)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('radicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicados.RadicadoRetoma')),
            ],
        ),
    ]
