# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0004_actividades'),
        ('formadores', '0007_auto_20160915_1733'),
        ('radicados', '0004_radicadoretoma'),
        ('region', '0002_auto_20160728_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado_text', models.CharField(blank=True, max_length=1000)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField(unique=True)),
                ('correo', models.EmailField(blank=True, max_length=100)),
                ('telefono_fijo', models.CharField(blank=True, max_length=100)),
                ('telefono_celular', models.CharField(blank=True, max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_beneficiario', to='matrices.Area')),
                ('diplomado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomado_beneficiario', to='productos.Diplomado')),
                ('formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formador_beneficiario', to='formadores.Formador')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiarioPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('diplomado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomado_beneficiariopendiente', to='productos.Diplomado')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grado_beneficiario', to='matrices.Grado'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_beneficiario', to='formadores.Grupos'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='radicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radicado_beneficiario', to='radicados.Radicado'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_beneficiario', to='region.Region'),
        ),
    ]
