# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 23:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='Carga Masiva/Archivo')),
                ('resultado', models.FileField(blank=True, null=True, upload_to='Carga Masiva/Resultado')),
                ('estado', models.CharField(default='Procesando...', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
