# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0002_auto_20160926_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='usuario_colombia_aprende',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
