# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0003_beneficiario_usuario_colombia_aprende'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='dane_ie_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='dane_sede_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='departamento_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='Diplomas'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_descarga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='ie_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='ip_descarga',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='municipio_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='secretaria_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='sede_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='zona_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
