# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0004_auto_20161021_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='dane_ie_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='dane_sede_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='departamento_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ie_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='municipio_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='secretaria_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='sede_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='zona_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
