# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0005_auto_20161024_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='ruta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
