# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrices', '0006_beneficiario_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='vigencia',
            field=models.CharField(default='2017', max_length=100),
            preserve_default=False,
        ),
    ]
