# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0007_auto_20170609_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='area_basica_producto_final',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='estado_producto_final',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nombre_producto_final',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
