# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-05 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0008_auto_20170613_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='vigencia',
        ),
    ]
