# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0009_remove_beneficiario_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='html',
            field=models.FileField(blank=True, null=True, upload_to='PLE/HTML'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='imagen_graficacion_ple',
            field=models.ImageField(blank=True, null=True, upload_to='PLE/Graficacion PLE'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='imagen_historieta',
            field=models.ImageField(blank=True, null=True, upload_to='PLE/Historietas'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='imagen_infografia',
            field=models.ImageField(blank=True, null=True, upload_to='PLE/Infografias'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='imagen_para_leer',
            field=models.ImageField(blank=True, null=True, upload_to='PLE/Imagen PARA LEER'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='link_ruta_sostenibilidad',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='para_hacer_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='para_hacer_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='para_hacer_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='para_hacer_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='para_leer',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
