# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0002_auto_20160728_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_created=True)),
                ('recepcion_solicitud', models.DateField()),
                ('entidad_remitente', models.CharField(max_length=100)),
                ('funcionario_remitente', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo_solicitud', models.FileField(upload_to='Requerimientos/Interventoria')),
                ('descripcion', models.TextField(max_length=5000)),
                ('tiempo_respuesta', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('fecha_respuesta', models.DateField()),
                ('medio_entrega', models.CharField(max_length=100)),
                ('observaciones', models.TextField(max_length=1000)),
                ('archivo_respuesta', models.FileField(upload_to='Requerimientos/Interventoria')),
                ('encargados', models.ManyToManyField(related_name='encargados_requerimiento', to=settings.AUTH_USER_MODEL)),
                ('region', models.ManyToManyField(related_name='region_requerimiento', to='region.Region')),
            ],
        ),
    ]
