# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='archivo_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='Requerimientos/Interventoria'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='archivo_solicitud',
            field=models.FileField(blank=True, null=True, upload_to='Requerimientos/Interventoria'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(blank=True, default='Abierto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
