# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_auto_20161007_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='funcionario_remitente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
