# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('cargos', '0002_auto_20160714_0837'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField()),
                ('correo_personal', models.EmailField(blank=True, max_length=100)),
                ('celular_personal', models.CharField(blank=True, max_length=100)),
                ('profesion', models.CharField(blank=True, max_length=100)),
                ('correo_corporativo', models.EmailField(blank=True, max_length=100)),
                ('celular_corporativo', models.CharField(blank=True, max_length=100)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('fecha_terminacion', models.DateField(blank=True, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, max_length=100)),
                ('eps', models.CharField(blank=True, max_length=100)),
                ('pension', models.CharField(blank=True, max_length=100)),
                ('arl', models.CharField(blank=True, max_length=100)),
                ('oculto', models.BooleanField(default=False)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.Banco')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Cargo')),
                ('region', models.ManyToManyField(to='region.Region')),
            ],
            options={
                'permissions': (('rh', 'Recursos Humanos'),),
            },
        ),
    ]
