# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='banco',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bancos.Banco'),
        ),
    ]
