# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativos', '0002_auto_20160826_1852'),
        ('administrativos', '0003_auto_20160714_1539'),
    ]

    operations = [
    ]
