# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociadores', '0003_soporte_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
