# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preinscripcion', '0002_docentespreinscritos_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercepcionInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=1000)),
                ('area_1', models.CharField(blank=True, max_length=1000)),
                ('antiguedad', models.CharField(blank=True, max_length=1000)),
                ('pregunta_1', models.CharField(blank=True, max_length=1000)),
                ('pregunta_1_1', models.CharField(blank=True, max_length=1000)),
                ('pregunta_2', models.CharField(blank=True, max_length=1000)),
                ('pregunta_3', models.CharField(blank=True, max_length=1000)),
                ('pregunta_4', models.CharField(blank=True, max_length=1000)),
                ('pregunta_5', models.CharField(blank=True, max_length=1000)),
                ('pregunta_6', models.CharField(blank=True, max_length=1000)),
                ('pregunta_6_1', models.CharField(blank=True, max_length=1000)),
                ('pregunta_7', models.CharField(blank=True, max_length=1000)),
                ('pregunta_8', models.CharField(blank=True, max_length=1000)),
                ('pregunta_9', models.CharField(blank=True, max_length=1000)),
                ('pregunta_10', models.CharField(blank=True, max_length=1000)),
                ('pregunta_11', models.CharField(blank=True, max_length=1000)),
                ('pregunta_12', models.CharField(blank=True, max_length=1000)),
                ('pregunta_12_1', models.CharField(blank=True, max_length=1000)),
                ('pregunta_13', models.CharField(blank=True, max_length=1000)),
                ('docente_preinscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.DocentesPreinscritos')),
            ],
        ),
    ]
