# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percepcioninicial',
            options={'ordering': ['docente_preinscrito__primer_nombre']},
        ),
    ]
