# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0004_auto_20161025_0939'),
        ('encuestas', '0002_auto_20160902_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercepcionFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=1000)),
                ('tiempo_formacion', models.CharField(blank=True, max_length=1000)),
                ('pregunta_1', models.CharField(blank=True, max_length=1000)),
                ('pregunta_2', models.CharField(blank=True, max_length=1000)),
                ('pregunta_3', models.CharField(blank=True, max_length=1000)),
                ('pregunta_4', models.CharField(blank=True, max_length=1000)),
                ('pregunta_5', models.CharField(blank=True, max_length=1000)),
                ('pregunta_6', models.CharField(blank=True, max_length=1000)),
                ('pregunta_7', models.CharField(blank=True, max_length=1000)),
                ('pregunta_8', models.CharField(blank=True, max_length=1000)),
                ('pregunta_9', models.CharField(blank=True, max_length=1000)),
                ('pregunta_10', models.CharField(blank=True, max_length=1000)),
                ('pregunta_11', models.CharField(blank=True, max_length=1000)),
                ('pregunta_12', models.CharField(blank=True, max_length=1000)),
                ('docente_preinscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.DocentesPreinscritos')),
            ],
            options={
                'ordering': ['docente_preinscrito__primer_nombre'],
            },
        ),
    ]
