# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_auditoria', models.IntegerField()),
                ('codigo_pais', models.IntegerField()),
                ('codigo_departamento', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('oculto', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
